graph-algorithms/edge-addition-planarity-suite

- Makefile.am
- c/planarityCommandLine.c
- c/samples/Makefile.am
- configure.ac
- test-samples.sh.in
The individual commits should explain themselves pretty well. Basically we tell autotools about the `c/samples` directory so that the samples can be installed automatically. The first commit is unrelated but trivial and should not change anything at all.
> Let autotools know about the samples

- Makefile.am
Autotools didn't know about the README.md or LICENSE.TXT files, so
they were neither included in the distribution tarball nor installed
to the user's system with "make install." Here we add the relevant
bits to the Makefile.am to include them in the release tarball,
and install them to the user's preferred --docdir.
> Makefile.am: ship the documentation and install it to $(docdir).

- planarity.1
Here is the rewritten version, including your changes, with only a trivial added change: I removed the trailing whitespaces you added.
The question "why .1 ?" has a simple answer: 1 is the relevant [section](https://en.wikipedia.org/wiki/Man_page#Manual_sections).
Cheers!
> Rewrite manpage

- c/g6-write-iterator.c
- c/planarity.c
- c/planarity.h
- c/planarityRandomGraphs.c
- c/planaritySpecificGraph.c
- c/planarityTestGraphFunctionality.c
Resolves #34
Confirmed both menu-driven transform and graph test flows work as their command-line flag-driven counterparts.
Fixed bug where `outputStr` didn't take ownership of string from the `testOutput` `strOrFile` after we `testAllGraphs`.
> Issue 34 - Menu-driven activation of graph transformation and algorithm

- TestSupport/generate_graphs.bat
- TestSupport/planarity_runner.bat
- TestSupport/testTableGenerator.py
- c/planaritySpecificGraph.c
- c/planarityTestGraphFunctionality.c
Resolves #64 and #67 
* `c/planaritySpecificGraph.c` - In `SpecificGraph()` we attach algorithm *after* reading the single graph in first so that we don't try to `EnsureArcCapacity()` (see issue descriptions for investigation and reasoning)
* `c/planarityTestGraphFunctionality.c` - In `testAllGraphs()`, if we are running with command `-(d34)`, we set the arc capacity to `(N * (N - 1))` up front so we will never try to increase the arc capacity after attaching those algorithm extensions.
* `TestSupport/` - updated `generate_graphs.bat` and `planarity_runner.bat` so that they generate files for `M = 0` and added error handling in `testTableGenerator.py` in case the `input_dir` isn't of the form `<root dir>\N\C` (i.e. we'll fail over to getting graph order and command run when we …
> Issue 64 and Issue 67 - `EnsureArcCapacity()` before attaching `-(d34)` algorithm extensions in `SpecificGraph()` and `testAllGraphs()`

- c/planarityTestGraphFunctionality.c
Resolves #82, resolves #83
* `c/planarityTestGraphFunctionality.c` - Adding missing `gp_Free(&copyOfOrigGraph)` calls to resolve memory leaks
* Planar Embedding and Kuratowski subgraph isolation
```
0 leaks for 0 total leaked bytes.
```
* Planar graph drawing by visibility representation (`-d`)
```
0 leaks for 0 total leaked bytes.
```
* Outerplanar embedding and obstruction isolation (`-o`)
```
0 leaks for 0 total leaked bytes.
```
* Search for subgraph homeomorphic to `K_{2,3}` (`-2`)
```
0 leaks for 0 total leaked bytes.
```
* Search for subgraph homeomorphic to `K_{3,3}` (`-3`)
```
0 leaks for 0 total leaked bytes.
```
* _**N.B.**_ Running `testAllGraphs()` for `K_{3, 3}` search takes a significantly longer period of time than any of the other tests. I have a hypothesis that there's …
> Issue 82 - resolving memory leak issues in `testAllGraphs()`

- TestSupport/planaritytesting/leaksorchestrator/planarity_leaks_config.ini
Follow-up to #59
Adding `planarity_leaks_config.ini` default config file to source control so that users will not have to run `planarity_leaks_config_manager.py` locally to generate it before updating the default values with the parameters necessary for their run.
> Adding `planarity_leaks_config.ini` default config file to source control

- TestSupport/planaritytesting/edge_deletion_analysis.py
- TestSupport/planaritytesting/graph.py
Resolves #79
* `TestSupport/planaritytesting/edge_deletion_analysis.py` - Generalized mechanism from #77 so that user may specify whether they wish to check the results of `K_{2, 3}` search, `K_{3, 3}` search, or `K_4` search to see if, for each `.g6` encoded graph in a `.g6` input file, the homeomorph search erroneously returned `OK` when in fact the graph contains a subgraph homeomorphic to the target homeomorph.
> Issue #79 - generalize edge deletion analysis tool

- .gitignore
- .vscode/launch.json
- Makefile.am
- c/planarityApp/planarity.1
- c/planarityApp/planarity.h
- c/planarityApp/planarityCommandLine.c
- c/planarityApp/planarityHelp.c
- c/planarityApp/planarityMenu.c
- c/planarityApp/planarityTestAllGraphs.c
- c/planarityApp/planarityTransformGraph.c
Resolves #94 
- `c/planarityApp/planarityTestGraphFunctionality.c` - split out into `planarityTransformGraph.c` and `planarityTestAllGraphs.c`
- `c/planarityApp/`
- `planarityTransformGraph.c` - Contains `TransformGraph()`, which is comprised of the first branch of the old `TestGraphFunctionality()` function
- `planarityTestAllGraphs.c` - Contains `TestAllGraphs()`, which is comprised of the second branch of the old `TestGraphFunctionality()` function. (note change in function signature, since Test All Graphs branch in old `TestGraphFunctionality()` function disallowed `inputStr`)
- `.vscode/launch.json` - Corrected Transform Graph example launch configuration command-line parameterization (i.e. `planarity -x -(gam) infileName outfileName` rather than `planarity -t -t(gam) infileName …
> Issue #94 - Separate Transform Graph and Test All Graphs functionality

- c/graphLib/homeomorphSearch/graphK23Search.c
- c/graphLib/homeomorphSearch/graphK33Search.c
- c/graphLib/homeomorphSearch/graphK4Search.c
- c/graphLib/planarityRelated/graphNonplanar.c
- c/graphLib/planarityRelated/graphOuterplanarObstruction.c
Closes #105 
The X-Y path being used for detection of minor E5 wasn't the lowest X-Y path, which is the same one needed to test for minor E4. Once the lowest X-Y path is identified for E4, if neither of its attachment points are below x and y, then the x-y path identified in that test is also the one needed for E5 because only the lowest x-y path could possibly have a Z-to-W path, since the containing bicomp is a planar embedding.
Also had to clean up code related to how the X-Y path marking functions were called, and what they return, to avoid writing the same undesirable pattern into the new method to be used in E4 and E5 testing.
> Fix for issue #105 plus pertinent code cleanup

- configure.ac
Two minor changes that the "autoupdate" program suggests:
* Quote the arguments to `AC_INIT`
* Replace `AC_PROG_LIBTOOL` with `LT_INIT`
> configure.ac: run autoupdate

- c/graphLib/extensionSystem/graphFunctionTable.h
- c/graphLib/graphStructures.h
Resolves #40 and #118
Extrapolated fix recommended by @orlitzky and verified semantics with @john-boyer-phd
* `c/graphLib/graphStructures.h` - now declare named struct `baseGraphStructure` and `typedef` that struct so that the `typedef` of `graphP` works (since `graphUtils.c` `#include`s `graphStructures.h`, there's no need to add the same`typedef` statements)
* `c/graphLib/extensionSystem/graphFunctionTable.h` - updated so that we can use `graphP` in parameter list (external linkage due to `typedef`)
Verified Debug and Release builds on all supported platforms, i.e. MacOS `clang`, Windows 10 (MinGW32 `gcc` and MSVC `cl`), and Debian 12.7 (`gcc` 12.2.0)
_**N.B.**_ I tried cloning the `gcc` [repository](https://gcc.gnu.org/git.html), but there's no branch yet for `gcc-15` (which is slated …
> Issues 40 and 118 - function pointer param fix

- c/graphLib/graphUtils.c
- c/graphLib/io/graphIO.c
- c/graphLib/io/strOrFile.c
- c/graphLib/lowLevelUtils/apiutils.c
- c/graphLib/lowLevelUtils/appconst.h
- c/planarityApp/planarity.h
- c/planarityApp/planarityCommandLine.c
- c/planarityApp/planarityHelp.c
- c/planarityApp/planarityMenu.c
- c/planarityApp/planarityTestAllGraphs.c
- c/planarityApp/planarityTransformGraph.c
- c/planarityApp/planarityUtils.c
- devEnvSetupAndDefaults/.vscode/tasks.json
Resolves #96 
* `devEnvSetupAndDefaults/.vscode/tasks.json` - Enable comprehensive warnings within all build commands; adding [`-Wextra`](https://clang.llvm.org/docs/DiagnosticsReference.html#wextra) to `clang` and [`-Wextra`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-W) to `gcc` (both Linux and MinGW32) build commands now yields largely the same warnings as those produced by MSVC `cl`, but are currently commented out and will be the subject of #123 . Additionally, I've chosen to ignore the following warnings issued by MSVC `cl` using the [`/wd`](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170) [compiler option](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=msvc-170): …
> Issue #96 - Resolve warnings from setting `-Wall` on `clang` and `gcc`

- .gitignore
- Makefile.am
- c/graph.h
- c/graphLib.h
- c/graphLib/graph.h
- c/graphLib/graphDFSUtils.c
- configure.ac
- libplanarity.pc.in
Resolves #122 
* `libplanarity.pc.in` - Based on [libbraiding.pc.in](https://github.com/miguelmarco/libbraiding/blob/master/libbraiding.pc.in)
* `c/graph.h` - convenience wrapper for backwards compatibility for users expecting `graph.h` to be at the root of the planarity `@includedir@`
* `c/graphLib.h` - convenience wrapper to expose planarity graph library functionality to downstream consumers
* `c/graphLib/graph.h` and `c/graphLib/graphDFSUtils.c` - removed `./` for relative `#include`s to match pattern in all other headers
* `.gitignore` - ignore generated files `libplanarity.pc` and `configure~`
* `configure.ac` - Added `PKG_INSTALLDIR` macro to set the default install directory, and added `AC_CONFIG_FILES([libplanarity.pc])` to ask for the creation of the `libplanarity.pc` by …
> Added prerequisites for pkg-config compatibility

- README.md
- devEnvSetupAndDefaults/.vscode/launch.json
- devEnvSetupAndDefaults/.vscode/tasks.json
Resolves #102 
_**N.B.**_ One must follow the updated [2. Dev Setup](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/2.-Dev-Setup) steps to install MSYS2 and then install the MinGW-w64 toolchain.
* `devEnvSetupAndDefaults/.vscode/tasks.json` - update `command` to use the `gcc.exe` installed as part of the MinGW-w64 toolchain
* `devEnvSetupAndDefaults/.vscode/launch.json` - update `miDebuggerPath` to use the `gdb.exe` installed as part of the MinGW-w64 toolchain 
* `README.md` - Instruct users to perform steps to build the distribution using the MSYS2 UCRT64 terminal app.
---
Confirmed that the distribution build process outlined in `README.md` successfully produces the expected `.tar.gz`.
Additionally, successfully hit breakpoints (e.g. within …
> Issue #102 - Add support for MinGW-w64 and deprecate MinGW 32 

- c/graphLib/lowLevelUtils/appconst.h
- c/graphLib/lowLevelUtils/platformTime.h
- devEnvSetupAndDefaults/.vscode/tasks.json
Resolves #120 
`FILE_DELIMETER` was being defined incorrectly due to incorrect OS check, which caused `outputTestAllGraphsResults()` in `planarityTestAllGraphs.c` to fail in finding the `finalSlash` within `infileName`.
* `c/graphLib/lowLevelUtils/appconst.h` - Should check if `_WIN32` is defined to determine if the OS is Windows according to the Pre-defined Compiler Macros Wiki page on [Operating Systems](https://sourceforge.net/p/predef/wiki/OperatingSystems/), which itself links to [64-Bit Compiler - Predefined macros](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/64-bit-compiler?redirectedfrom=MSDN#predefined-macros).
* `c/graphLib/lowLevelUtils/platformTime.h` - should check against `WINDOWS` rather than `WIN32` for the above reason, as well as the fact that …
> Issue #120 -  Fixing how we determine whether the OS is Windows so that `FILE_DELIMETER` is correctly defined for MSVC `cl`

- c/graphLib/io/g6-write-iterator.c
Resolves #71 
* `c/graphLib/io/g6-write-iterator.c` - auto-formatting fixed up inconsistencies in whitespace etc.; in `_printEncodedGraph()`, after writing the `pG6WriteIterator->currGraphBuff` to `pG6WriteIterator->g6Output`, added another call to `sf_fputs()` to write `"\n"` to the `strOrFile` so that only one `.g6` encoded graph appears per line.
---
Verified that underlying `fputs()` call to write `"\n"` to file outputs the correct line terminator per-platform:
* On MacOS, each line was terminated with `\n`
* On Windows (both MinGW-w64 `gcc` and MSVC `cl`), each line was terminated with `\r\n`
* On Debian Linux, each line was terminated with `\n`
> Issue #71 - Add platform-appropriate line terminator between `.g6` encoded graphs in `.g6` output file

- c/planarityApp/planarity.h
- c/planarityApp/planarityMenu.c
- c/planarityApp/planarityUtils.c
Resolves #98 
* `c/planarityApp/planarityMenu.c` - When prompting users for filenames, I first construct a format string that limits the number of characters being read using `scanf()`, then pass this constructed format string to `scanf()` when trying to populate `infileName` and `outfileName` in both `TransformGraphMenu()` and `TestAllGraphsMenu()`
_**N.B.**_ The changes to `c/planarityApp/planarity.h` and `c/planarityApp/planarityUtils.c` are changes that will come from merging #131 
---
Verified both Transform Graph and Test All Graphs menu interactions on MacOS (`clang`), Windows (MinGW-w64 `gcc` and MSVC `cl`), and Debian Linux (`gcc`).
> Issue #98 - Build format string to use with `scanf()` when prompting user for filenames in `TransformGraphMenu()` and `TestAllGraphsMenu()`

- .gitignore
- Makefile.am
- README.md
- autogen.sh
- configure.ac
- devEnvSetupAndDefaults/devEnvSetup.sh
Resolves #46 
* `autogen.sh` - One must now run `autoreconf -fi` instead of the `autogen.sh` script as the first step of the autotools build process.
* _**N.B.**_ `autogen.sh` was introduced in [85e191](https://github.com/graph-algorithms/edge-addition-planarity-suite/commit/85e1918a84b1bce4ea8a8378440c9a18997959b4) and updated in #1 and #6 (see #5 )
* `.gitignore` - Ignore `m4` directory, as well as intermediate files from build process
* `configure.ac` - added `AC_CONFIG_MACRO_DIRS([m4])` (see [autoconf manual - Input](https://www.gnu.org/software/autoconf/manual/autoconf-2.70/html_node/Input.html)) to specify the `m4` directory as the location of additional local Autoconf macros
* `Makefile.am` - Added `ACLOCAL_AMFLAGS = -I m4` for where `.m4` files are to be copied
* `README.md` - …
> Issue #46 - Resolve suggestions and warnings for autotools build process

- c/graphLib/graphStructures.h
- c/graphLib/graphUtils.c
- c/graphLib/homeomorphSearch/graphK33Search_Extensions.c
- c/graphLib/homeomorphSearch/graphK4Search_Extensions.c
- c/graphLib/io/strOrFile.c
- c/graphLib/lowLevelUtils/appconst.h
- c/graphLib/planarityRelated/graphDrawPlanar_Extensions.c
- c/planarityApp/planarityCommandLine.c
- devEnvSetupAndDefaults/.vscode/tasks.json
Resolves #24
Updated [1. Project Overview - Optimization of 1-Based Array Indexing](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/1.-Project-Overview#optimization-of-1-based-array-indexing) to reflect the change to how we manage 0-based vs. 1-based array indexing using the `-DUSE_0BASEDARRAYS`/`/D USE_0BASEDARRAYS` compiler option controlling the preprocessor.
* `c/graphLib/io/strOrFile.c` - need to `#include <stdint.h>` for the definitions for `INT32_MIN`/`MAX`; this was not discovered during #140, although tests were performed on a MacBook pro with `clang`. I found a [StackOverflow response](https://stackoverflow.com/a/19440917) suggesting that perhaps `clang`'s `stdlib.h` includes `stdint.h` for internal purposes, which *might* have been why compilation/running …
> Issue #24 - Use compiler preprocessor option to Signal 1-based versus 0-based Array Indexing

- devEnvSetupAndDefaults/.vscode/tasks.json
I discovered a `.dSYM` Archived Debug Symbols file was being generated alongside the `Release` executable on MacOS using `clang`. A [StackOverflow reply](https://stackoverflow.com/a/76328264) has revealed that this is due to including `-g` flag in the `devEnvSetupAndDefaults/.vscode/tasks.json` default build configuration, which means that debug artifacts will be built to accompany both `Debug` *and* `Release` builds. I just verified that I’m able to hit a breakpoint in the `Release` executable when the `-g` flag is used to compile the executable, and that I fail to hit any breakpoint when `-g` is absent (no `.dSYM` debug symbols generated).
Looking at the size of `Release` executables produced, it's probably worthwhile to show users how to produce a leaner `Release` build using VSCode if …
> VSCode Release build configurations should make generating debug symbols optional

- Makefile.am
When compiling on certain architectures, the following error message is produced:
```
Makefile.am:93: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined
```
This pull request specifies the `pkgconfigdir` to address that error.
> Specify `pkgconfigdir` in `Makefile.am`

- .github/workflows/compile-warnings.yml
- .github/workflows/compilers.yml
- .github/workflows/os.yml
- .github/workflows/runtests.yml
- .github/workflows/sanitisers.yml
- .github/workflows/spelling.yml
This pull request adds some continuous integration checks that will be triggered when new pull requests are made. In particular, the tests:
* check for compiler warnings;
* check that the tests pass using a variety of different clang and gcc versions;
* check that the tests pass on the systems Alpine, Cygwin, macOS, Ubuntu with aarch64, and Ubuntu with arm;
* run an address sanitizer, undefined behaviour sanitizer and valgrind; and
* checks for spelling mistakes.
> Add some continuous integration checks

- Makefile.am
- configure.ac
- m4/ax_append_compile_flags.m4
- m4/ax_append_flag.m4
- m4/ax_check_compile_flag.m4
- m4/ax_compiler_flags_cflags.m4
- m4/ax_require_defined.m4
This PR adds the flag `--enable-compile-warnings` which enables a slew of compiler warnings. These are the compiler flags used by the Digraphs package for GAP as reported in #147. 
I thought this would be a good place to start with resolving #147 so that it is possible to recreate the warnings here.
> Add `--enable-compile-warnings` configure flag

- .github/workflows/os.yml
In response to @john-boyer-phd's comment in #151, and to #152, this pull request adds workflow jobs that checks the tests pass on various windows systems using `MSYS2`, and on Debian. It also gets rid of the the dependency on `gap-actions/setup-cygwin`.
> Add workflow jobs for Windows and Debian 

- c/graphLib/homeomorphSearch/graphK33Search.c
If one comments out line 237 (i.e. `#define USE_MERGEBLOCKER`), then when one compiles, one gets the error:
```
call to undeclared function '_IsolateMinorE2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```
This is because the `extern` (defined in `graphIsolator.c`) was simply commented out:
```
// extern int _IsolateMinorE2(graphP theGraph);
```
Rather than enclosed in `#ifndef USE_MERGEBLOCKER` (since the calling code in `_RunExtraK33Tests()` is run only when `USE_MERGEBLOCKER` is not defined)
---
On a related note, there are other `extern`s that are commented out that might require review:
* `// extern int K33SEARCH_ID;`
* `// extern void _ClearVisitedFlags(graphP);`
* `// extern int  _GetBicompSize(graphP theGraph, int …
> In `graphK33Search.c`, enclose `extern` declaration of `_IsolateMinorE2()` with `#ifndef USE_MERGEBLOCKER`
